[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "foo_package"
author = "Yoav"
author-email = "yoavklein25@gmail.com"
classifiers = [ "License :: OSI Approved :: MIT License",]

